# Generated by Django 2.1.5 on 2024-04-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
