# Generated by Django 3.2.6 on 2024-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_auto_20240412_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='step',
            field=models.CharField(choices=[('SOLICITUD_EN_LINEA', 'Solicitud En Linea'), ('AUTENTICACION_DEL_CLIENTE', 'Autenticacion Del Cliente'), ('INFORMACION_BASICA', 'Informacion Basica'), ('PRESENTACION_Y_ACEPTACION_DE_LA_OFERTA', 'Presentacion Y Aceptacion De La Oferta'), ('FIRMA_DE_DOCUMENTOS', 'Firma De Documentos'), ('CARGUE_DE_DOCUMENTOS', 'Cargue De Documentos'), ('CONFIRMACION_Y_ACTIVACION', 'Confirmacion Y Activacion')], max_length=255, null=True),
        ),
    ]
