# Generated by Django 2.1.5 on 2024-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creditCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creditLimit', models.IntegerField()),
            ],
        ),
    ]
