# Generated by Django 3.2.6 on 2024-04-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20240412_1700'),
        ('CreditCard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.client'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='creditCardProfile',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BLACK', 'Black')], default='STANDARD', max_length=10),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='franchise',
            field=models.CharField(choices=[('MASTERCARD', 'Mastercard'), ('VISA', 'Visa')], default='MASTERCARD', max_length=10),
        ),
    ]
