# Generated by Django 3.2.6 on 2024-04-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0002_auto_20240412_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
